### ISSUE TITLE
Overlapping text on "News & Insights" page 

### ISSUE THREAD

**Issue by CoralineAda** [ContributorCovenant/ethicalsource#127]
It happens on the blog index page (https://ethicalsource.dev/blog/) between roughly 600px 800px browser window width. Perhaps the media queries need to be adjusted?

<img width="265" alt="Screenshot 2023-02-28 at 2 11 28 PM" src="https://user-images.githubusercontent.com/22284/221967575-c87ab2f1-f5aa-4e45-8856-5f68e0b09964.png">

**Comment by tlarkin011** [comment]
I would love to help out!

**Comment by CoralineAda** [comment]
@tlarkin011 Have at it! Let me know if you need any help or support, and please tag me in for review.

**Comment by tlarkin011** [comment]
@CoralineAda Thank you!

**Comment by jerdog** [comment]
Looks like it starts to happen at 642px
![image](https://github.com/user-attachments/assets/fcce65ae-7b40-434f-8b25-1307b87bcfb3)

and then fully overlaps at 641px
![image](https://github.com/user-attachments/assets/065f993d-d3a5-4349-ab14-240a58deb401)

I am not sure that the media query will make that much of a difference because once it hits 639px, it goes back to a normal view
![image](https://github.com/user-attachments/assets/7c7d6d06-fcf7-4b59-8ac9-59a4445324ec)

It's likely a CSS thing and I will take a look to see what pops up
